
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/afds?serverTimezone=UTC
        username: root
        password: root
        
    jpa:
        database: mysql
        show-sql: true
        hibernate.ddl-auto: update
    
    freemarker:
        suffix: .html
        cache: false
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/templates/, classpath:/templates/Angular/, classpath:/templates/css/, classpath:/templates/email_templates/, classpath:/templates/font-awesome/, classpath:/templates/fonts/, classpath:/texplates/img/, classpath:/templates/js